server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  profiles:
    active: local
  cloud:
    gateway:
      server:
        webflux:
          routes:
            #系统服务
            - id: system-service
              uri: http://localhost:8091
              predicates:
                - Path=/api/system/**
              filters:
                - StripPrefix=1
            #文件服务
            - id: file-service
              uri: http://localhost:8092
              predicates:
                - Path=/api/file/**
              filters:
                - StripPrefix=1
            #报表服务
            - id: report-service
              uri: http://localhost:8093
              predicates:
                - Path=/api/report/**
              filters:
                - StripPrefix=1

#springdoc配置
springdoc:
  swagger-ui:
    # 手动聚合所有服务的 API 文档
    urls:
      - name: 系统服务
        url: /api/system/v3/api-docs    # 该路径会被上面的 user-service 路由规则匹配
      - name: 文件服务
        url: /api/file/v3/api-docs
      - name: 报表服务
        url: /api/report/v3/api-docs
    # 可选：自定义网关的Swagger UI访问路径
    path: /swagger-ui.html

#token相关配置
token:
  secret: my-secret-key
  headerName: token
  expireTime: 3600

#白名单配置
security:
  ignore:
    whites:
      - /*/v3/api-docs
      - /report/*
      - /file/*
      - /system/*